/**
 * Embed data/*.json into src/builtins.ts, so the library works without file
 * access (e.g. in a browser). Run after editing a dataset:
 *
 *     npm run gen
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseJson, stringifyJson } from "../src/json.ts";

export const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
export const DATA = join(ROOT, "data");
export const BUILTINS_FILE = join(ROOT, "src", "builtins.ts");

/** The contents src/builtins.ts should have for the current data/ directory. */
export function renderBuiltins(): string {
  const files = readdirSync(DATA).filter((f) => f.endsWith(".json")).sort();
  const lines = files.map((f) => {
    const compact = stringifyJson(parseJson(readFileSync(join(DATA, f), "utf8")), 0);
    return `  ${JSON.stringify(f.slice(0, -5))}: ${JSON.stringify(compact)},`;
  });
  return `// Generated by scripts/gen_builtins.ts from data/*.json. Do not edit; run \`npm run gen\`.

/** Built-in distributions: name -> JSON spec text. */
export const BUILTIN_SPECS: Readonly<Record<string, string>> = {
${lines.join("\n")}
};
`;
}

export function writeBuiltins(): void {
  writeFileSync(BUILTINS_FILE, renderBuiltins());
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeBuiltins();
  console.log(`wrote ${BUILTINS_FILE}`);
}
